theme: jekyll-theme-minimal
title: Dominick Nguyen
description: Hi! I'm a student at UC San Diego working on a degree in Applied Math. I also interned at Facebook. This is a place to motivate me to post learnings, thoughts, and projects!
